<?php

namespace Tests\Unit\Controllers;

use App\Models\Advert;
use Illuminate\Http\Response;
use PHPUnit\Framework\TestCase;

class AdvertControllerTest extends TestCase
{
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    /**
     * A basic unit test example.
     *
     * @return void
     */
    public function testIndexController() {
        $response = $this->json('get', '/api/advert', ['name' => 'Sally']);
        $response
            ->assertStatus(201);
    }



}
